name: Deploy Products API

on: workflow_dispatch

env:
  INFRASTRUCTURE_DIRECTORY: "Infrastructure"

jobs:
  deploy:
    name: Deploy ProductsAPI with AWS CDK
    runs-on: ubuntu-latest
    steps:
      - name: Set environment
        run: |
          case ${GITHUB_REF##*/} in
            "production") echo "ENVIRONMENT=production" >> $GITHUB_ENV ;;
            "preprod") echo "ENVIRONMENT=preprod" >> $GITHUB_ENV ;;
            "qa") echo "ENVIRONMENT=qa" >> $GITHUB_ENV ;;
            *) echo "ENVIRONMENT=development" >> $GITHUB_ENV ;;
          esac

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ secrets.AWS_REGION }}

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Install dependencies
        working-directory: ${{ env.INFRASTRUCTURE_DIRECTORY }}
        run: npm install

      - name: CDK Synth
        working-directory: ${{ env.INFRASTRUCTURE_DIRECTORY }}
        run: cdk synth

      - name: CDK Deploy
        working-directory: ${{ env.INFRASTRUCTURE_DIRECTORY }}
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          SERVICE: ${{ env.SERVICE }}
        run: cdk deploy --require-approval never

